import React, { useEffect, useRef, useState } from 'react'
import { api, getToken } from '../api.js'
import { Btn, Card, Empty, Err, Note, Pill, Spin, fmtMs } from '../ui.jsx'

/** The answer as a reader wants it. `plain` drops the [1] markers: the citation is still
 *  attached to the answer in the response, it is simply not shown. */
const Answer = ({ text, onCite, plain }) => {
  const body = String(text || '')
  if (plain) return <>{body.replace(/\s*\[\d+\]/g, '').replace(/\s+([.,;:])/g, '$1').trim()}</>
  return (
    <>
      {body.split(/(\[\d+\])/g).map((p, i) => {
        const m = p.match(/^\[(\d+)\]$/)
        return m ? <span key={i} className="cite" onClick={() => onCite(Number(m[1]))}>[{m[1]}]</span>
                 : <span key={i}>{p}</span>
      })}
    </>
  )
}

function status(m) {
  const g = m.grounding || {}
  if (g.flag === 'deterministic_table') {
    return { label: 'GROUNDED', tone: 'good', note: 'Computed directly from the table, not generated by the model.' }
  }
  if (g.flag === 'insufficient_evidence') {
    const missing = (g.sufficiency?.missing || []).join(', ')
    return { label: 'INSUFFICIENT EVIDENCE', tone: 'bad',
             note: missing ? `Your documents do not state ${missing}.` : 'Your documents do not answer this question.' }
  }
  if (g.flag === 'low_relevance') {
    return { label: 'INSUFFICIENT EVIDENCE', tone: 'bad',
             note: `No passage came close enough (best match ${Math.round((g.best_score || 0) * 100)}%).` }
  }
  if (m.refused) {
    const reason = { unsupported_values: `Blocked: ${(g.unsupported_values || []).join(', ')} appear in the answer but not in the sources.`,
                     hedged_language: 'Blocked: the answer hedged instead of citing a source.',
                     uncited: 'Blocked: the answer carried no citation.',
                     model_refused: 'The model found nothing to support an answer.' }[g.flag]
    return { label: 'INSUFFICIENT EVIDENCE', tone: 'bad', note: reason || 'Not answered from your documents.' }
  }
  if (g.verified) {
    return { label: 'GROUNDED', tone: 'good', note: 'Every value in this answer was traced back to a cited passage.' }
  }
  return { label: 'PARTIALLY GROUNDED', tone: 'warn',
           note: (g.dropped_sentences || []).length
             ? `${g.dropped_sentences.length} unsupported sentence(s) were removed before showing this.`
             : 'Some of this answer could not be traced to a cited passage.' }
}

function Confidence({ m }) {
  const g = m.grounding || {}
  const st = status(m)
  const match = g.best_score != null ? Math.round(g.best_score * 100) : null
  const suff = g.sufficiency?.score != null ? Math.round(g.sufficiency.score * 100) : null
  return (
    <div className="verdict">
      <div className="row">
        <Pill tone={st.tone}>{st.label}</Pill>
        {match != null && <Pill title="Cosine similarity of the best passage">Best match {match}%</Pill>}
        {suff != null && <Pill title="How completely the evidence covers the question">Evidence {suff}%</Pill>}
        {m.citations?.length > 0 && <Pill>{m.citations.length} citation{m.citations.length > 1 ? 's' : ''}</Pill>}
      </div>
      <Note>{st.note}</Note>
    </div>
  )
}

function Verdict({ g, timing, model }) {
  if (!g) return null
  const p = []
  if (timing?.exact_hits) p.push(<Pill key="e">{timing.exact_hits} exact code match</Pill>)
  if (timing?.graph_hits) p.push(<Pill key="gh">{timing.graph_hits} from the entity graph</Pill>)
  if (timing?.rerank_ms != null) p.push(<Pill key="rr">Reranked {timing.candidates || 0} candidates</Pill>)
  if (timing?.embed_ms != null) p.push(<Pill key="s">Retrieval {Math.round(timing.embed_ms + timing.search_ms)} ms</Pill>)
  if (timing?.llm_tokens_per_sec) p.push(<Pill key="tp">{timing.llm_tokens_per_sec} tok/s</Pill>)
  if (timing?.llm_ttft_ms) p.push(<Pill key="ft">First word in {fmtMs(timing.llm_ttft_ms)}</Pill>)
  if (model) p.push(<Pill key="m" title={model}>{String(model).split(/[\\/]/).pop()}</Pill>)
  if (!p.length) return null
  return <div className="chips" style={{ marginTop: 10 }}>{p}</div>
}

export default function Ask({ sys, settings, setSettings, suggestions, setSource, prefill, clearPrefill }) {
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [recording, setRecording] = useState(false)
  const [speakOn, setSpeakOn] = useState(false)
  const end = useRef(null)
  const qStart = useRef(null)
  const audio = useRef(null)

  // keep the question and its answer in view, rather than scrolling past them to the evidence
  useEffect(() => { qStart.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }, [messages.length])
  useEffect(() => { if (prefill) { setInput(prefill); clearPrefill?.() } }, [prefill])

  // Read the answer aloud. The Windows speech engine is used when it is available (better voices,
  // fully offline); otherwise the browser's own speech engine reads it, so this never silently does
  // nothing. Citation markers are stripped so it does not say "bracket one".
  const browserSpeak = (text) => {
    try {
      const synth = window.speechSynthesis
      if (!synth) return false
      synth.cancel()
      const u = new SpeechSynthesisUtterance(text.replace(/\[\d+\]/g, '').replace(/\s+/g, ' ').trim())
      u.rate = 1.0
      u.lang = 'en-IN'
      synth.speak(u)
      return true
    } catch { return false }
  }

  const speak = async (text) => {
    if (!speakOn || !text) return
    const clean = text.replace(/\[\d+\]/g, '').trim()
    if (sys?.voice?.tts) {
      try {
        const res = await fetch(api.speakUrl(), { method: 'POST',
          headers: { 'Content-Type': 'application/json', ...(getToken() ? { Authorization: `Bearer ${getToken()}` } : {}) },
          body: JSON.stringify({ text: clean }) })
        if (res.ok) {
          audio.current?.pause()
          audio.current = new Audio(URL.createObjectURL(await res.blob()))
          audio.current.play().catch(() => browserSpeak(clean))
          return
        }
      } catch { /* fall through to the browser voice */ }
    }
    if (!browserSpeak(clean)) setError('No speech engine is available in this browser.')
  }

  const ask = async (question, heard, docIds) => {
    const q = (question ?? input).trim()
    if (!q || busy) return
    setInput(''); setBusy(true); setError('')
    const i = messages.length + 1
    setMessages((m) => [...m, { role: 'user', text: q, heard }, { role: 'assistant', text: '' }])
    const patch = (fn) => setMessages((m) => m.map((msg, idx) => (idx === i ? fn(msg) : msg)))
    await api.askStream({ question: q, tuning: settings.tuning, top_k: settings.top_k, ...(docIds ? { doc_ids: docIds } : {}) }, {
      onRoute: (r) => patch((m) => ({ ...m, route: r })),
      onSources: (ev) => patch((m) => ({ ...m, sources: ev.sources })),
      onToken: (t) => patch((m) => ({ ...m, text: m.text + t })),
      onDone: (ev) => {
        // What the reader has already read stays on screen. The final event may carry a
        // tidied or shortened version; swapping it in makes the answer appear to rewrite
        // itself a second after it finished, which reads as a bug even when the new text is
        // fine. The final text is used only when nothing was streamed (a refusal, an error).
        patch((m) => ({ ...m,
                        text: (m.text || '').trim() ? m.text : ev.answer,
                        sources: ev.sources || m.sources, citations: ev.citations,
                        grounding: ev.grounding, timing: ev.timing, model: ev.model, refused: ev.refused,
                        route: ev.route || m.route }))
        // read aloud exactly what is on screen
        patch((m) => { speak(m.text || ev.answer); return m })
      },
      // An error after the answer has been read is reported beside it, never on top of it.
      onError: (e) => {
        setError(String(e.message || e))
        patch((m) => ((m.text || '').trim() ? m : { ...m, text: `⚠ ${e.message}` }))
      },
    })
    setBusy(false)
  }

  const mic = async () => {
    setRecording(true); setError('')
    try {
      const r = await api.listen()
      setRecording(false)
      await ask(r.text, r.heard !== r.text ? r.heard : undefined)
    } catch (e) { setRecording(false); setError(`Voice: ${e.message}`) }
  }

  const last = [...messages].reverse().find((m) => m.role === 'assistant' && m.citations)
  const cite = (msg, n) => {
    const s = (msg.sources || []).find((x) => x.n === n)
    if (s) setSource(s)
  }

  return (
    <div className="wrap">
      <Card>
        <div className="row" style={{ marginBottom: 14 }}>
          <div className="spacer" />
          {settings.show_evidence && last?.route && (
            <Pill tone="accent" title={Object.values(last.route.reasons || {}).join(' · ')}>
              Route: {last.route.routes.join(' + ')}</Pill>)}
        </div>

        <div className="msgs">
          {messages.length === 0 && (
            <Empty>Ask your knowledge base. Every answer is grounded in your own documents, with the page shown.</Empty>
          )}
          {messages.map((m, i) => (
            m.role === 'user' ? (
              <div key={i} ref={i === messages.length - 2 ? qStart : null}>
                <div className="qline">“{m.text}”</div>
                {m.heard && <Note>heard: {m.heard}</Note>}
              </div>
            ) : (
              <div key={i}>
                <div className={`answer ${m.refused ? 'refused' : ''}`}>
                  {m.text
                    ? <Answer text={m.text} onCite={(n) => cite(m, n)} plain={!settings.show_evidence} />
                    : <Spin />}
                </div>
                {settings.show_evidence && m.grounding && <Confidence m={m} />}
                {settings.show_evidence && <Verdict g={m.grounding} timing={m.timing} model={m.model} />}
              </div>
            )
          ))}
        </div>

        {suggestions?.length > 0 && messages.length === 0 && (
          <div style={{ marginTop: 18 }}>
            <h3 className="sectionLabel">Summaries</h3>
            <div className="recos">
              {suggestions.map((s) => (
                <button className="reco" key={s.question} onClick={() => ask(s.question, undefined, s.doc_ids)}>
                  <span>{s.question}</span><span className="arrow">→</span>
                </button>
              ))}
            </div>
            <Note style={{ marginTop: 8 }}>
              One per document you have indexed. Type any question of your own in the box above.
            </Note>
          </div>
        )}

        <div className="composer">
          <input placeholder="Ask anything…" value={input} disabled={busy}
                 onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && ask()} />
          <Btn onClick={() => (sys?.voice?.stt
                 ? mic()
                 : setError(sys?.voice?.stt_error
                            || 'Dictation needs the Windows speech packages. Run scripts\\doctor.ps1 once, '
                               + 'then restart the app. Reading answers aloud already works.'))}
               disabled={busy}
               title={sys?.voice?.stt ? 'Ask by voice' : 'Dictation is not installed yet'}>
            {recording ? '● Listening' : '🎤'}
          </Btn>
          <Btn onClick={() => { const on = !speakOn; setSpeakOn(on); if (!on) { window.speechSynthesis?.cancel(); audio.current?.pause() } }}
               kind={speakOn ? 'primary' : ''}
               title={sys?.voice?.tts ? 'Read answers aloud (Windows voice)' : 'Read answers aloud (browser voice)'}>
            🔊</Btn>
          <Btn kind="primary" onClick={() => ask()} disabled={busy || !input.trim()}>↑</Btn>
        </div>
        {error && <div style={{ marginTop: 10 }}><Err>{error}</Err></div>}
      </Card>
    </div>
  )
}
